# Generated by Django 3.1.7 on 2021-03-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
