# Generated by Django 3.1.7 on 2021-03-05 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_namespecializaion_vacancy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NameSpecializaion',
            new_name='NameSpecialization',
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': "City's"},
        ),
        migrations.AlterModelOptions(
            name='namespecialization',
            options={'verbose_name': 'Specialization/Profession', 'verbose_name_plural': 'Names Specializations'},
        ),
    ]
