# Generated by Django 3.1.7 on 2021-03-06 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_auto_20210305_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Vacancy'},
        ),
    ]
