# Generated by Django 3.1.7 on 2021-03-11 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0008_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_data', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.city')),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.nameprof')),
            ],
            options={
                'unique_together': {('city', 'prof')},
            },
        ),
    ]
