# Generated by Django 3.1.7 on 2021-03-11 16:18

from django.db import migrations, models
import scraping.models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0009_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url_data',
            field=models.TextField(default=scraping.models.default_urls),
        ),
    ]
