# Generated by Django 3.1.7 on 2021-03-12 06:33

from django.db import migrations
import scraping.models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0011_auto_20210311_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errors',
            name='data',
            field=scraping.models.JSONField1(),
        ),
        migrations.AlterField(
            model_name='url',
            name='url_data',
            field=scraping.models.JSONField1(default=scraping.models.default_urls),
        ),
    ]
