# Generated by Django 3.1.7 on 2021-03-12 06:38

from django.db import migrations
import scraping.models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0012_auto_20210312_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url_data',
            field=scraping.models.JSONField1(),
        ),
    ]
