# Generated by Django 3.1.7 on 2021-03-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0014_auto_20210312_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Vacancy'},
        ),
        migrations.AddField(
            model_name='vacancy',
            name='earning',
            field=models.CharField(default=1, max_length=200, verbose_name='Зарплата'),
            preserve_default=False,
        ),
    ]
