# Generated by Django 3.1.7 on 2021-03-17 17:19

from django.db import migrations
import scraping.models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0015_auto_20210313_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errors',
            name='data',
            field=scraping.models.JSONField1(default={}),
        ),
    ]
